runtime: nodejs16

instance_class: F2

env_variables: 
  BUCKET_NAME: "careerkeentech"

handlers:
- url: /
  static_files: theme/index.html
  upload: theme/index.html

- url: /
  static_dir: theme 